const doctors = [
  {
    id: 1,
    fullName: "Dr. Ahmed Raza",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Cardiology",
    experienceYears: 12,
    consultationFee: 3000,
    rating: 4.7,
    totalReviews: 120,
    isAvailableToday: true,
    verified: true,
    bioShort: "Expert in heart disease prevention.",
  },
  {
    id: 2,
    fullName: "Dr. Sana Malik",
    gender: "Female",
    city: "Lahore",
    specialization: "Dermatology",
    experienceYears: 8,
    consultationFee: 2500,
    rating: 4.5,
    totalReviews: 95,
    isAvailableToday: false,
    verified: true,
    bioShort: "Specialist in skin and cosmetic care.",
  },
  {
    id: 3,
    fullName: "Dr. Bilal Khan",
    gender: "Male",
    city: "Karachi",
    specialization: "Neurology",
    experienceYears: 15,
    consultationFee: 4000,
    rating: 4.8,
    totalReviews: 210,
    isAvailableToday: true,
    verified: true,
    bioShort: "Experienced neurologist treating complex cases.",
  },
  {
    id: 4,
    fullName: "Dr. Hira Shahid",
    gender: "Female",
    city: "Lahore",
    specialization: "Urology",
    experienceYears: 6,
    consultationFee: 2200,
    rating: 4.3,
    totalReviews: 70,
    isAvailableToday: true,
    verified: false,
    bioShort: "Focused on urinary tract disorders.",
  },
  {
    id: 5,
    fullName: "Dr. Usman Tariq",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Dermatology",
    experienceYears: 10,
    consultationFee: 2700,
    rating: 4.6,
    totalReviews: 110,
    isAvailableToday: false,
    verified: true,
    bioShort: "Advanced skin and hair treatments.",
  },
  {
    id: 6,
    fullName: "Dr. Ayesha Iqbal",
    gender: "Female",
    city: "Islamabad",
    specialization: "Cardiology",
    experienceYears: 9,
    consultationFee: 3500,
    rating: 4.9,
    totalReviews: 180,
    isAvailableToday: true,
    verified: true,
    bioShort: "Interventional cardiology expert.",
  },
  {
    id: 7,
    fullName: "Dr. Hamza Farooq",
    gender: "Male",
    city: "Karachi",
    specialization: "Orthopedics",
    experienceYears: 11,
    consultationFee: 3200,
    rating: 4.4,
    totalReviews: 140,
    isAvailableToday: true,
    verified: false,
    bioShort: "Joint and sports injury specialist.",
  },
  {
    id: 8,
    fullName: "Dr. Rabia Noor",
    gender: "Female",
    city: "Lahore",
    specialization: "Neurology",
    experienceYears: 7,
    consultationFee: 2800,
    rating: 4.2,
    totalReviews: 60,
    isAvailableToday: false,
    verified: true,
    bioShort: "Treating neurological disorders.",
  },
  {
    id: 9,
    fullName: "Dr. Imran Qureshi",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Urology",
    experienceYears: 13,
    consultationFee: 3000,
    rating: 4.6,
    totalReviews: 130,
    isAvailableToday: true,
    verified: true,
    bioShort: "Experienced urologist for kidney and prostate.",
  },
  {
    id: 10,
    fullName: "Dr. Mahnoor Ali",
    gender: "Female",
    city: "Islamabad",
    specialization: "Dermatology",
    experienceYears: 5,
    consultationFee: 2000,
    rating: 4.1,
    totalReviews: 50,
    isAvailableToday: true,
    verified: false,
    bioShort: "Pediatric skin care specialist.",
  },
  {
    id: 11,
    fullName: "Dr. Saad Hassan",
    gender: "Male",
    city: "Karachi",
    specialization: "Cardiology",
    experienceYears: 14,
    consultationFee: 4200,
    rating: 4.8,
    totalReviews: 220,
    isAvailableToday: false,
    verified: true,
    bioShort: "Specialist in complex heart procedures.",
  },
  {
    id: 12,
    fullName: "Dr. Muneeba Aslam",
    gender: "Female",
    city: "Lahore",
    specialization: "Pediatrics",
    experienceYears: 6,
    consultationFee: 2300,
    rating: 4.5,
    totalReviews: 85,
    isAvailableToday: true,
    verified: true,
    bioShort: "Child growth and preventive care.",
  },
  {
    id: 13,
    fullName: "Dr. Faisal Javed",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Orthopedics",
    experienceYears: 10,
    consultationFee: 3100,
    rating: 4.3,
    totalReviews: 100,
    isAvailableToday: true,
    verified: false,
    bioShort: "Fracture and spine specialist.",
  },
  {
    id: 14,
    fullName: "Dr. Komal Yousaf",
    gender: "Female",
    city: "Islamabad",
    specialization: "Neurology",
    experienceYears: 9,
    consultationFee: 3600,
    rating: 4.7,
    totalReviews: 150,
    isAvailableToday: false,
    verified: true,
    bioShort: "Neurological disorder management.",
  },
  {
    id: 15,
    fullName: "Dr. Danish Akhtar",
    gender: "Male",
    city: "Karachi",
    specialization: "Urology",
    experienceYears: 12,
    consultationFee: 3300,
    rating: 4.6,
    totalReviews: 125,
    isAvailableToday: true,
    verified: true,
    bioShort: "Kidney and bladder treatment expert.",
  },
  {
    id: 16,
    fullName: "Dr. Amina Khalid",
    gender: "Female",
    city: "Lahore",
    specialization: "Cardiology",
    experienceYears: 8,
    consultationFee: 3400,
    rating: 4.9,
    totalReviews: 175,
    isAvailableToday: true,
    verified: true,
    bioShort: "Heart care and interventional cardiology.",
  },
  {
    id: 17,
    fullName: "Dr. Talha Mehmood",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Dermatology",
    experienceYears: 7,
    consultationFee: 2600,
    rating: 4.2,
    totalReviews: 65,
    isAvailableToday: false,
    verified: false,
    bioShort: "Eczema and psoriasis specialist.",
  },
  {
    id: 18,
    fullName: "Dr. Saba Zahid",
    gender: "Female",
    city: "Islamabad",
    specialization: "Pediatrics",
    experienceYears: 11,
    consultationFee: 2900,
    rating: 4.4,
    totalReviews: 105,
    isAvailableToday: true,
    verified: true,
    bioShort: "Child immunization and nutrition expert.",
  },
  {
    id: 19,
    fullName: "Dr. Noman Latif",
    gender: "Male",
    city: "Karachi",
    specialization: "Orthopedics",
    experienceYears: 16,
    consultationFee: 4500,
    rating: 4.8,
    totalReviews: 240,
    isAvailableToday: true,
    verified: true,
    bioShort: "Joint and trauma surgery expert.",
  },
  {
    id: 20,
    fullName: "Dr. Zara Siddiqui",
    gender: "Female",
    city: "Lahore",
    specialization: "Urology",
    experienceYears: 6,
    consultationFee: 2400,
    rating: 4.3,
    totalReviews: 75,
    isAvailableToday: true,
    verified: false,
    bioShort: "Urinary and reproductive health care.",
  },
];
export default doctors;
