const doctors = [
  {
    id: 1,
    fullName: "Dr. Ahmed Raza",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Pulmonologist",
    experienceYears: 12,
    consultationFee: 3000,
    rating: 4.7,
    totalReviews: 120,
    isAvailableToday: true,
    verified: true,
    bioShort: "Treats asthma, breathing issues and lung diseases.",
  },
  {
    id: 2,
    fullName: "Dr. Sana Malik",
    gender: "Female",
    city: "Lahore",
    specialization: "Dermatologist",
    experienceYears: 8,
    consultationFee: 2500,
    rating: 4.5,
    totalReviews: 95,
    isAvailableToday: false,
    verified: true,
    bioShort: "Skin, acne and cosmetic dermatology treatments.",
  },
  {
    id: 3,
    fullName: "Dr. Bilal Khan",
    gender: "Male",
    city: "Karachi",
    specialization: "Neurologist",
    experienceYears: 15,
    consultationFee: 4000,
    rating: 4.8,
    totalReviews: 210,
    isAvailableToday: true,
    verified: true,
    bioShort: "Treats brain, nerve and neurological disorders.",
  },
  {
    id: 4,
    fullName: "Dr. Hira Shahid",
    gender: "Female",
    city: "Lahore",
    specialization: "Urologist",
    experienceYears: 6,
    consultationFee: 2200,
    rating: 4.3,
    totalReviews: 70,
    isAvailableToday: true,
    verified: false,
    bioShort: "Kidney, bladder and urinary tract treatments.",
  },
  {
    id: 5,
    fullName: "Dr. Usman Tariq",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Dermatologist",
    experienceYears: 10,
    consultationFee: 2700,
    rating: 4.6,
    totalReviews: 110,
    isAvailableToday: false,
    verified: true,
    bioShort: "Hair loss, acne and advanced skin care.",
  },
  {
    id: 6,
    fullName: "Dr. Ayesha Iqbal",
    gender: "Female",
    city: "Islamabad",
    specialization: "Gynecologist",
    experienceYears: 9,
    consultationFee: 3500,
    rating: 4.9,
    totalReviews: 180,
    isAvailableToday: true,
    verified: true,
    bioShort: "Women's reproductive health and pregnancy care.",
  },
  {
    id: 7,
    fullName: "Dr. Hamza Farooq",
    gender: "Male",
    city: "Karachi",
    specialization: "Orthopedic Surgeon",
    experienceYears: 11,
    consultationFee: 3200,
    rating: 4.4,
    totalReviews: 140,
    isAvailableToday: true,
    verified: false,
    bioShort: "Bone, joint and sports injury treatments.",
  },
  {
    id: 8,
    fullName: "Dr. Rabia Noor",
    gender: "Female",
    city: "Lahore",
    specialization: "Neurologist",
    experienceYears: 7,
    consultationFee: 2800,
    rating: 4.2,
    totalReviews: 60,
    isAvailableToday: false,
    verified: true,
    bioShort: "Treatment for migraines and nerve disorders.",
  },
  {
    id: 9,
    fullName: "Dr. Imran Qureshi",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Urologist",
    experienceYears: 13,
    consultationFee: 3000,
    rating: 4.6,
    totalReviews: 130,
    isAvailableToday: true,
    verified: true,
    bioShort: "Kidney stones and prostate care specialist.",
  },
  {
    id: 10,
    fullName: "Dr. Mahnoor Ali",
    gender: "Female",
    city: "Islamabad",
    specialization: "Child Specialist",
    experienceYears: 5,
    consultationFee: 2000,
    rating: 4.1,
    totalReviews: 50,
    isAvailableToday: true,
    verified: false,
    bioShort: "Child growth monitoring and pediatric care.",
  },
  {
    id: 11,
    fullName: "Dr. Saad Hassan",
    gender: "Male",
    city: "Karachi",
    specialization: "Gastroenterologist",
    experienceYears: 14,
    consultationFee: 4200,
    rating: 4.8,
    totalReviews: 220,
    isAvailableToday: false,
    verified: true,
    bioShort: "Digestive system and liver disease specialist.",
  },
  {
    id: 12,
    fullName: "Dr. Muneeba Aslam",
    gender: "Female",
    city: "Lahore",
    specialization: "Child Specialist",
    experienceYears: 6,
    consultationFee: 2300,
    rating: 4.5,
    totalReviews: 85,
    isAvailableToday: true,
    verified: true,
    bioShort: "Preventive healthcare and vaccinations for children.",
  },
  {
    id: 13,
    fullName: "Dr. Faisal Javed",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Orthopedic Surgeon",
    experienceYears: 10,
    consultationFee: 3100,
    rating: 4.3,
    totalReviews: 100,
    isAvailableToday: true,
    verified: false,
    bioShort: "Fracture management and spine treatments.",
  },
  {
    id: 14,
    fullName: "Dr. Komal Yousaf",
    gender: "Female",
    city: "Islamabad",
    specialization: "Eye Specialist",
    experienceYears: 9,
    consultationFee: 3600,
    rating: 4.7,
    totalReviews: 150,
    isAvailableToday: false,
    verified: true,
    bioShort: "Vision correction and cataract treatments.",
  },
  {
    id: 15,
    fullName: "Dr. Danish Akhtar",
    gender: "Male",
    city: "Karachi",
    specialization: "ENT Specialist",
    experienceYears: 12,
    consultationFee: 3300,
    rating: 4.6,
    totalReviews: 125,
    isAvailableToday: true,
    verified: true,
    bioShort: "Ear, nose, throat and sinus treatments.",
  },
  {
    id: 16,
    fullName: "Dr. Amina Khalid",
    gender: "Female",
    city: "Lahore",
    specialization: "Gynecologist",
    experienceYears: 8,
    consultationFee: 3400,
    rating: 4.9,
    totalReviews: 175,
    isAvailableToday: true,
    verified: true,
    bioShort: "Specialist in pregnancy and women's health.",
  },
  {
    id: 17,
    fullName: "Dr. Talha Mehmood",
    gender: "Male",
    city: "Faisalabad",
    specialization: "Obesity Specialist",
    experienceYears: 7,
    consultationFee: 2600,
    rating: 4.2,
    totalReviews: 65,
    isAvailableToday: false,
    verified: false,
    bioShort: "Weight management and metabolic health care.",
  },
  {
    id: 18,
    fullName: "Dr. Saba Zahid",
    gender: "Female",
    city: "Islamabad",
    specialization: "Child Specialist",
    experienceYears: 11,
    consultationFee: 2900,
    rating: 4.4,
    totalReviews: 105,
    isAvailableToday: true,
    verified: true,
    bioShort: "Child nutrition and immunization expert.",
  },
  {
    id: 19,
    fullName: "Dr. Noman Latif",
    gender: "Male",
    city: "Karachi",
    specialization: "Dentist",
    experienceYears: 16,
    consultationFee: 4500,
    rating: 4.8,
    totalReviews: 240,
    isAvailableToday: true,
    verified: true,
    bioShort: "Dental implants, braces and cosmetic dentistry.",
  },
  {
    id: 20,
    fullName: "Dr. Zara Siddiqui",
    gender: "Female",
    city: "Lahore",
    specialization: "Sexologist",
    experienceYears: 6,
    consultationFee: 2400,
    rating: 4.3,
    totalReviews: 75,
    isAvailableToday: true,
    verified: false,
    bioShort: "Sexual health and relationship counseling.",
  },
];

export default doctors;
